import { Service } from '../models/Service.js';
import { Category } from '../models/Category.js';

interface ServiceSeed {
  shortName: string;
  title: string;
  categorySlug: string;
  provider: string;
  description: string;
  type: 'Software' | 'Hardware' | 'Software/Hardware';
  trl: { current: number; expected: number };
  license: string;
  standards: string[];
  inputs: { name: string; description: string }[];
  outputs: { name: string; description: string }[];
  interactsWith: string[];
  potentialUseCases: string[];
  repositoryTable: 'INTACT_TOOLBOX' | 'OTHER_SERVICES';
}

// Table 1: INTACT Toolbox Services
const intactToolboxServices: ServiceSeed[] = [
  {
    shortName: 'ULANCS-PTI',
    title: 'Joint Security-vs-QoS Modelling/Game Optimisation Tool',
    categorySlug: 'predictive-threat-intelligence',
    provider: 'ULANCS',
    description:
      'Intelligent selection of countermeasures balancing security effectiveness and QoS impact using game-theoretic optimization.',
    type: 'Software',
    trl: { current: 4, expected: 7 },
    license: 'TBD',
    standards: ['STIX', 'MITRE ATT&CK'],
    inputs: [{ name: 'Threat Data', description: 'STIX-formatted threat intelligence' }],
    outputs: [{ name: 'Countermeasure Plan', description: 'Optimized security configuration' }],
    interactsWith: ['MONT-MMT', 'UBI-MAESTRO'],
    potentialUseCases: ['Network security optimization', 'QoS-aware threat mitigation'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'MONT-NFZ',
    title: 'Montimage Network Fuzzer',
    categorySlug: 'ai-attack-defence-emulation',
    provider: 'MONT',
    description:
      'Generates malicious traffic by mutating nominal traffic patterns for security testing.',
    type: 'Software',
    trl: { current: 4, expected: 7 },
    license: 'Open Source (MIT)',
    standards: ['MITRE ATT&CK'],
    inputs: [{ name: 'Network Traffic', description: 'PCAP or live traffic capture' }],
    outputs: [{ name: 'Fuzzed Traffic', description: 'Mutated malicious traffic patterns' }],
    interactsWith: ['MONT-MMT', 'AIRBUS-ORION'],
    potentialUseCases: ['Protocol fuzzing', 'Security testing', 'Attack simulation'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'SBA-SPLIT',
    title: 'SPLIT - Security Protocol Testing Toolkit',
    categorySlug: 'ai-attack-defence-emulation',
    provider: 'SBA',
    description: 'Automated security protocol analysis and vulnerability testing toolkit.',
    type: 'Software',
    trl: { current: 5, expected: 7 },
    license: 'Proprietary',
    standards: ['CVE', 'CWE'],
    inputs: [{ name: 'Protocol Specification', description: 'Protocol definition files' }],
    outputs: [{ name: 'Vulnerability Report', description: 'Security analysis results' }],
    interactsWith: ['SBA-CAST'],
    potentialUseCases: ['Protocol security testing', 'Vulnerability assessment'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'SBA-CAST',
    title: 'CAST - Combinatorial API Security Testing Tool',
    categorySlug: 'ai-attack-defence-emulation',
    provider: 'SBA',
    description: 'Automated combinatorial testing for API security vulnerabilities.',
    type: 'Software',
    trl: { current: 5, expected: 7 },
    license: 'Proprietary',
    standards: ['OWASP', 'CVE'],
    inputs: [{ name: 'API Specification', description: 'OpenAPI/Swagger specification' }],
    outputs: [{ name: 'Security Report', description: 'API vulnerability findings' }],
    interactsWith: ['SBA-SPLIT'],
    potentialUseCases: ['API security testing', 'Penetration testing'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'AIRBUS-ORION',
    title: 'Orion Malware Detection',
    categorySlug: 'automated-threat-inspection',
    provider: 'AIRBUS',
    description: 'Advanced malware detection system using machine learning techniques.',
    type: 'Software',
    trl: { current: 5, expected: 7 },
    license: 'Proprietary',
    standards: ['MITRE ATT&CK', 'YARA'],
    inputs: [{ name: 'Binary Files', description: 'Executable files for analysis' }],
    outputs: [{ name: 'Detection Results', description: 'Malware classification and IOCs' }],
    interactsWith: ['MONT-MMT', 'HMU-DASH'],
    potentialUseCases: ['Malware analysis', 'Threat hunting', 'Incident response'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'BEYOND-DD',
    title: 'Data Diode',
    categorySlug: 'automated-threat-inspection',
    provider: 'BEYOND',
    description:
      'Hardware-based unidirectional data transfer for air-gapped network protection.',
    type: 'Hardware',
    trl: { current: 7, expected: 9 },
    license: 'Proprietary',
    standards: ['IEC 62443', 'NERC CIP'],
    inputs: [{ name: 'Network Data', description: 'Data stream for secure transfer' }],
    outputs: [{ name: 'Secured Data', description: 'Unidirectionally transferred data' }],
    interactsWith: ['MONT-MMT'],
    potentialUseCases: ['Critical infrastructure protection', 'OT/IT segregation'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'MONT-MMT',
    title: 'Montimage Monitoring Tool (MMT)',
    categorySlug: 'automated-threat-inspection',
    provider: 'MONT',
    description:
      'Real-time network traffic analysis and security monitoring with deep packet inspection.',
    type: 'Software',
    trl: { current: 8, expected: 9 },
    license: 'Open Source (MIT)',
    standards: ['MITRE ATT&CK', 'Zeek'],
    inputs: [{ name: 'Network Traffic', description: 'Live or captured network traffic' }],
    outputs: [
      { name: 'Security Events', description: 'Detected threats and anomalies' },
      { name: 'Network Metrics', description: 'Traffic statistics and KPIs' },
    ],
    interactsWith: ['MONT-NFZ', 'AIRBUS-ORION', 'UBI-MAESTRO', 'AEGIS-COS'],
    potentialUseCases: ['Network monitoring', 'Intrusion detection', 'Traffic analysis'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'SIEMENS-ROSCO',
    title: 'Runtime Security Pipeline (ROSCO-eBPF)',
    categorySlug: 'automated-threat-inspection',
    provider: 'SIEMENS',
    description: 'eBPF-based runtime security monitoring for containerized environments.',
    type: 'Software',
    trl: { current: 7, expected: 8 },
    license: 'Apache 2.0/MIT',
    standards: ['MITRE ATT&CK', 'CIS Benchmarks'],
    inputs: [{ name: 'System Events', description: 'Kernel and container events' }],
    outputs: [{ name: 'Security Alerts', description: 'Runtime security violations' }],
    interactsWith: ['UBI-MAESTRO', 'HMU-DASH'],
    potentialUseCases: ['Container security', 'Runtime protection', 'Kubernetes security'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'TUC-NIDS',
    title: 'FPGA-NIDS (Network Intrusion Detection System)',
    categorySlug: 'automated-threat-inspection',
    provider: 'TUC',
    description: 'Hardware-accelerated network intrusion detection using FPGA technology.',
    type: 'Software/Hardware',
    trl: { current: 5, expected: 6 },
    license: 'Open Source',
    standards: ['Snort', 'Suricata'],
    inputs: [{ name: 'Network Traffic', description: 'High-speed network packets' }],
    outputs: [{ name: 'Intrusion Alerts', description: 'Detected network attacks' }],
    interactsWith: ['MONT-MMT'],
    potentialUseCases: ['High-speed intrusion detection', 'Line-rate packet inspection'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'K3Y-K3CR',
    title: 'K3CyberRadar (K3CR) Probes',
    categorySlug: 'automated-threat-inspection',
    provider: 'K3Y',
    description: 'Distributed probes for network security monitoring and threat detection.',
    type: 'Software',
    trl: { current: 6, expected: 7 },
    license: 'TBD',
    standards: ['MITRE ATT&CK'],
    inputs: [{ name: 'Network Interfaces', description: 'Network tap points' }],
    outputs: [{ name: 'Security Telemetry', description: 'Network security data' }],
    interactsWith: ['HMU-DASH', 'K3Y-TRUSTEE'],
    potentialUseCases: ['Distributed monitoring', 'Network visibility'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'SIEMENS-LLM',
    title: 'LLM Threat Modelling Tool',
    categorySlug: 'automated-threat-inspection',
    provider: 'SIEMENS',
    description: 'Large Language Model-based automated threat modeling and analysis.',
    type: 'Software',
    trl: { current: 7, expected: 8 },
    license: 'Apache 2.0/MIT',
    standards: ['STRIDE', 'MITRE ATT&CK'],
    inputs: [{ name: 'System Description', description: 'Architecture and design documents' }],
    outputs: [{ name: 'Threat Model', description: 'Identified threats and mitigations' }],
    interactsWith: ['K3Y-TRUSTEE'],
    potentialUseCases: ['Automated threat modeling', 'Security assessment'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'SBA-DID',
    title: 'Zero-trust Distributed Computing (DID/SSI)',
    categorySlug: 'zero-trust-architecture',
    provider: 'SBA',
    description: 'Decentralized identity management for zero-trust architectures.',
    type: 'Software',
    trl: { current: 4, expected: 7 },
    license: 'Proprietary',
    standards: ['W3C DID', 'W3C VC'],
    inputs: [{ name: 'Identity Claims', description: 'Verifiable credentials' }],
    outputs: [{ name: 'Identity Verification', description: 'Verified identity assertions' }],
    interactsWith: ['BEYOND-HSM'],
    potentialUseCases: ['Zero-trust access control', 'Decentralized authentication'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'BEYOND-HSM',
    title: 'Distributed Hardware Security Module',
    categorySlug: 'zero-trust-architecture',
    provider: 'BEYOND',
    description: 'Distributed Hardware Security Module for key management.',
    type: 'Software/Hardware',
    trl: { current: 3, expected: 7 },
    license: 'Proprietary',
    standards: ['PKCS#11', 'FIPS 140-2'],
    inputs: [{ name: 'Cryptographic Requests', description: 'Key operations' }],
    outputs: [{ name: 'Cryptographic Results', description: 'Signed/encrypted data' }],
    interactsWith: ['SBA-DID'],
    potentialUseCases: ['Secure key management', 'Distributed cryptography'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'FRAUNHOFER-TA',
    title: 'Twinning Agents',
    categorySlug: 'digital-twin-construction',
    provider: 'FRAUNHOFER',
    description: 'Agents for digital twin data synchronization and lifecycle management.',
    type: 'Software',
    trl: { current: 4, expected: 7 },
    license: 'Varies',
    standards: ['OPC UA', 'MQTT'],
    inputs: [{ name: 'Physical System Data', description: 'Sensor and operational data' }],
    outputs: [{ name: 'Digital Twin State', description: 'Synchronized twin representation' }],
    interactsWith: ['SIEMENS-PAC', 'UBI-MAESTRO'],
    potentialUseCases: ['Digital twin synchronization', 'Asset management'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'SIEMENS-PAC',
    title: 'PAC2200 Digital Shadow',
    categorySlug: 'digital-twin-construction',
    provider: 'SIEMENS',
    description: 'Digital shadow implementation for Siemens PAC2200 power meters.',
    type: 'Software',
    trl: { current: 5, expected: 7 },
    license: 'Proprietary',
    standards: ['IEC 61850', 'Modbus'],
    inputs: [{ name: 'Power Meter Data', description: 'PAC2200 measurements' }],
    outputs: [{ name: 'Digital Shadow', description: 'Real-time device representation' }],
    interactsWith: ['FRAUNHOFER-TA'],
    potentialUseCases: ['Energy monitoring', 'Grid security'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'HMU-DASH',
    title: 'Interactive HITL Dashboard',
    categorySlug: 'user-interface',
    provider: 'HMU',
    description: 'Human-in-the-loop dashboard for security monitoring and decision support.',
    type: 'Software',
    trl: { current: 4, expected: 6 },
    license: 'TBD',
    standards: ['WCAG 2.1'],
    inputs: [{ name: 'Security Events', description: 'Alerts and metrics from tools' }],
    outputs: [{ name: 'Visualization', description: 'Interactive security dashboards' }],
    interactsWith: ['AIRBUS-ORION', 'MONT-MMT', 'K3Y-K3CR', 'SIEMENS-ROSCO'],
    potentialUseCases: ['Security operations center', 'Incident response'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'K3Y-TRUSTEE',
    title: 'TRUSTEE Explainable AI Tool',
    categorySlug: 'explainable-ai',
    provider: 'K3Y',
    description: 'Explainable AI tool for interpreting security ML model decisions.',
    type: 'Software',
    trl: { current: 5, expected: 7 },
    license: 'TBD',
    standards: ['IEEE P7001'],
    inputs: [{ name: 'ML Predictions', description: 'Model outputs and features' }],
    outputs: [{ name: 'Explanations', description: 'Human-readable decision rationale' }],
    interactsWith: ['AIRBUS-ORION', 'SIEMENS-LLM', 'K3Y-K3CR'],
    potentialUseCases: ['Model transparency', 'Audit compliance'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'AXON-OSSR',
    title: 'Open Security Service Repository (OSSR)',
    categorySlug: 'service-management',
    provider: 'AXON',
    description: 'Central repository for security service catalog and management.',
    type: 'Software',
    trl: { current: 5, expected: 7 },
    license: 'Apache 2.0/MIT',
    standards: ['OpenAPI'],
    inputs: [{ name: 'Service Metadata', description: 'Service descriptions and configs' }],
    outputs: [{ name: 'Service Catalog', description: 'Searchable service registry' }],
    interactsWith: ['UBI-MAESTRO'],
    potentialUseCases: ['Service discovery', 'Security toolbox management'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'THALES-CR',
    title: 'CyberRange',
    categorySlug: 'training-simulation',
    provider: 'THALES',
    description: 'Cyber range platform for security training and exercises.',
    type: 'Software',
    trl: { current: 5, expected: 7 },
    license: 'Proprietary',
    standards: ['NICE Framework'],
    inputs: [{ name: 'Training Scenarios', description: 'Exercise configurations' }],
    outputs: [{ name: 'Training Results', description: 'Performance metrics and reports' }],
    interactsWith: ['UBI-MAESTRO'],
    potentialUseCases: ['Security training', 'Red team exercises', 'Skill assessment'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'UBI-MAESTRO',
    title: 'MAESTRO Service Orchestrator',
    categorySlug: 'orchestration',
    provider: 'UBI',
    description: 'Central orchestrator for deploying and managing security services.',
    type: 'Software',
    trl: { current: 5, expected: 7 },
    license: 'Open (Model TBD)',
    standards: ['Kubernetes', 'Helm'],
    inputs: [{ name: 'Deployment Specs', description: 'Service topology definitions' }],
    outputs: [{ name: 'Deployed Services', description: 'Running service instances' }],
    interactsWith: ['MONT-MMT', 'AXON-OSSR', 'FRAUNHOFER-TA', 'THALES-CR', 'AEGIS-COS'],
    potentialUseCases: ['Service deployment', 'Scenario orchestration'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
  {
    shortName: 'AEGIS-COS',
    title: 'COS - Cyber Orchestration Service (Message Broker)',
    categorySlug: 'infrastructure',
    provider: 'AEGIS',
    description: 'Central message broker for inter-service communication.',
    type: 'Software',
    trl: { current: 4, expected: 6 },
    license: 'Proprietary',
    standards: ['Apache Kafka', 'AMQP'],
    inputs: [{ name: 'Messages', description: 'Events and data from services' }],
    outputs: [{ name: 'Routed Messages', description: 'Delivered messages to subscribers' }],
    interactsWith: ['MONT-MMT', 'UBI-MAESTRO'],
    potentialUseCases: ['Event streaming', 'Service integration'],
    repositoryTable: 'INTACT_TOOLBOX',
  },
];

// Table 2: Related Infrastructure & Use Case Services
const infrastructureServices: ServiceSeed[] = [
  {
    shortName: 'CORE-01',
    title: 'Free5GC',
    categorySlug: '5g-core',
    provider: 'Open Source',
    description: '5G Core functions (NRF, AMF, SMF, UDM, etc.)',
    type: 'Software',
    trl: { current: 7, expected: 8 },
    license: 'Apache-2.0',
    standards: ['3GPP'],
    inputs: [{ name: '5G NAS', description: '5G NAS signaling' }],
    outputs: [{ name: 'Core Services', description: '5G core network services' }],
    interactsWith: ['RAN-01'],
    potentialUseCases: ['PUC1 - 5G Security'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'CORE-02',
    title: 'Open5GS',
    categorySlug: '5g-core',
    provider: 'Open Source',
    description: 'Alternative 5G Core Stack',
    type: 'Software',
    trl: { current: 7, expected: 8 },
    license: 'AGPL-3.0',
    standards: ['3GPP'],
    inputs: [{ name: '5G NAS', description: '5G NAS signaling' }],
    outputs: [{ name: 'Core Services', description: '5G core network services' }],
    interactsWith: ['RAN-01'],
    potentialUseCases: ['PUC1 - 5G Security'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'RAN-01',
    title: 'srsRAN + UERANSIM',
    categorySlug: '5g-ran',
    provider: 'Open Source',
    description: 'Simulated gNodeB and UE behavior',
    type: 'Software',
    trl: { current: 7, expected: 8 },
    license: 'AGPL-3.0',
    standards: ['3GPP'],
    inputs: [{ name: 'RF Signals', description: 'Radio frequency signals' }],
    outputs: [{ name: 'RAN Services', description: 'Radio access network services' }],
    interactsWith: ['CORE-01', 'CORE-02'],
    potentialUseCases: ['PUC1 - 5G Security'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'RAN-02',
    title: 'USRP',
    categorySlug: '5g-ran',
    provider: 'Open Source',
    description: 'Universal Software Radio Peripheral',
    type: 'Hardware',
    trl: { current: 8, expected: 9 },
    license: 'Various',
    standards: ['SDR'],
    inputs: [{ name: 'RF Signals', description: 'Radio frequency input' }],
    outputs: [{ name: 'Digital Samples', description: 'Digitized radio samples' }],
    interactsWith: ['RAN-01'],
    potentialUseCases: ['PUC1 - 5G Security'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'UE-01',
    title: 'Android UE',
    categorySlug: 'user-equipment',
    provider: 'Commercial',
    description: 'Mobile phone as UE',
    type: 'Hardware',
    trl: { current: 9, expected: 9 },
    license: 'Commercial',
    standards: ['3GPP'],
    inputs: [{ name: 'User Input', description: 'User interactions' }],
    outputs: [{ name: 'Network Traffic', description: 'Mobile network traffic' }],
    interactsWith: ['RAN-01'],
    potentialUseCases: ['PUC1 - 5G Security'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'TOOL-01',
    title: '5Greplay',
    categorySlug: 'attack-emulation',
    provider: 'Open Source',
    description: '5G network traffic replay for attack simulation',
    type: 'Software',
    trl: { current: 6, expected: 7 },
    license: 'MIT',
    standards: ['PCAP'],
    inputs: [{ name: 'PCAP Files', description: 'Captured 5G traffic' }],
    outputs: [{ name: 'Replayed Traffic', description: 'Simulated attack traffic' }],
    interactsWith: ['MONT-MMT'],
    potentialUseCases: ['PUC1 - 5G Security'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'TOOL-02',
    title: 'Cybel CyberRange',
    categorySlug: 'training-simulation',
    provider: 'THALES',
    description: 'Comprehensive cyber range platform',
    type: 'Software',
    trl: { current: 7, expected: 8 },
    license: 'Proprietary',
    standards: ['NICE Framework'],
    inputs: [{ name: 'Scenarios', description: 'Training scenario definitions' }],
    outputs: [{ name: 'Training Environment', description: 'Simulated cyber environment' }],
    interactsWith: ['THALES-CR'],
    potentialUseCases: ['PUC1 - 5G Security'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'HE-01',
    title: 'Radiology Medical VM',
    categorySlug: 'healthcare-equipment',
    provider: '5YPE',
    description: 'DICOM traffic simulation (MRI/CT scans)',
    type: 'Software',
    trl: { current: 6, expected: 7 },
    license: 'Proprietary',
    standards: ['DICOM', 'HL7'],
    inputs: [{ name: 'Medical Images', description: 'DICOM image data' }],
    outputs: [{ name: 'DICOM Traffic', description: 'Medical imaging network traffic' }],
    interactsWith: ['MONT-MMT'],
    potentialUseCases: ['PUC2 - Healthcare Security'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'HE-02',
    title: 'Withings Wearable VM',
    categorySlug: 'healthcare-equipment',
    provider: '5YPE',
    description: 'ECG and SpO2 monitoring simulation',
    type: 'Software',
    trl: { current: 6, expected: 7 },
    license: 'Proprietary',
    standards: ['HL7 FHIR'],
    inputs: [{ name: 'Vital Signs', description: 'ECG and SpO2 data' }],
    outputs: [{ name: 'Health Data', description: 'Wearable health metrics' }],
    interactsWith: ['MONT-MMT'],
    potentialUseCases: ['PUC2 - Healthcare Security'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'HE-03',
    title: 'Anaesthesia Machine VM',
    categorySlug: 'healthcare-equipment',
    provider: '5YPE',
    description: 'Operating room anaesthesia machine simulation',
    type: 'Software',
    trl: { current: 6, expected: 7 },
    license: 'Proprietary',
    standards: ['IEC 62443'],
    inputs: [{ name: 'Patient Data', description: 'Anaesthesia parameters' }],
    outputs: [{ name: 'Machine Data', description: 'Anaesthesia machine telemetry' }],
    interactsWith: ['MONT-MMT'],
    potentialUseCases: ['PUC2 - Healthcare Security'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'VIRT-01',
    title: 'Kubernetes',
    categorySlug: 'virtualization',
    provider: 'Open Source',
    description: 'Container orchestration platform',
    type: 'Software',
    trl: { current: 9, expected: 9 },
    license: 'Apache-2.0',
    standards: ['OCI', 'CRI'],
    inputs: [{ name: 'Container Specs', description: 'Kubernetes manifests' }],
    outputs: [{ name: 'Running Containers', description: 'Orchestrated containers' }],
    interactsWith: ['UBI-MAESTRO'],
    potentialUseCases: ['All Use Cases'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'VIRT-02',
    title: 'Proxmox',
    categorySlug: 'virtualization',
    provider: 'Open Source',
    description: 'VM and LXC container platform',
    type: 'Software',
    trl: { current: 9, expected: 9 },
    license: 'AGPL-3.0',
    standards: ['KVM', 'LXC'],
    inputs: [{ name: 'VM Configs', description: 'Virtual machine configurations' }],
    outputs: [{ name: 'Running VMs', description: 'Virtual machines and containers' }],
    interactsWith: ['VIRT-01'],
    potentialUseCases: ['PUC4 - Smart Grid'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'NET-01',
    title: 'GNS3',
    categorySlug: 'network-simulation',
    provider: 'Open Source',
    description: 'Switching and routing simulation',
    type: 'Software',
    trl: { current: 8, expected: 9 },
    license: 'GPL-3.0',
    standards: ['Various'],
    inputs: [{ name: 'Network Topology', description: 'Network design' }],
    outputs: [{ name: 'Simulated Network', description: 'Virtual network environment' }],
    interactsWith: ['NET-02'],
    potentialUseCases: ['PUC4 - Smart Grid'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'NET-02',
    title: 'Mininet',
    categorySlug: 'network-simulation',
    provider: 'Open Source',
    description: 'Network emulation',
    type: 'Software',
    trl: { current: 8, expected: 9 },
    license: 'BSD-3-Clause',
    standards: ['OpenFlow'],
    inputs: [{ name: 'Topology Script', description: 'Python topology definition' }],
    outputs: [{ name: 'Emulated Network', description: 'Software-defined network' }],
    interactsWith: ['NET-01'],
    potentialUseCases: ['PUC4 - Smart Grid'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'MON-01',
    title: 'Grafana',
    categorySlug: 'monitoring',
    provider: 'Open Source',
    description: 'Data visualization platform',
    type: 'Software',
    trl: { current: 9, expected: 9 },
    license: 'AGPL-3.0',
    standards: ['Prometheus', 'InfluxDB'],
    inputs: [{ name: 'Metrics', description: 'Time-series metrics data' }],
    outputs: [{ name: 'Dashboards', description: 'Interactive visualizations' }],
    interactsWith: ['MON-02', 'MONT-MMT'],
    potentialUseCases: ['All Use Cases'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'MON-02',
    title: 'InfluxDB',
    categorySlug: 'monitoring',
    provider: 'Open Source',
    description: 'Metrics storage',
    type: 'Software',
    trl: { current: 9, expected: 9 },
    license: 'MIT',
    standards: ['InfluxQL', 'Flux'],
    inputs: [{ name: 'Metrics', description: 'Time-series data points' }],
    outputs: [{ name: 'Query Results', description: 'Aggregated metrics' }],
    interactsWith: ['MON-01'],
    potentialUseCases: ['All Use Cases'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'SEC-01',
    title: 'Kafka',
    categorySlug: 'security-tools',
    provider: 'Open Source',
    description: 'Event streaming platform',
    type: 'Software',
    trl: { current: 9, expected: 9 },
    license: 'Apache-2.0',
    standards: ['Apache Kafka'],
    inputs: [{ name: 'Events', description: 'Event messages' }],
    outputs: [{ name: 'Streams', description: 'Event streams to consumers' }],
    interactsWith: ['AEGIS-COS'],
    potentialUseCases: ['All Use Cases'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'SEC-02',
    title: 'OpenVPN',
    categorySlug: 'security-tools',
    provider: 'Open Source',
    description: 'Secure remote access',
    type: 'Software',
    trl: { current: 9, expected: 9 },
    license: 'GPL-2.0',
    standards: ['OpenVPN'],
    inputs: [{ name: 'Network Traffic', description: 'Traffic to tunnel' }],
    outputs: [{ name: 'Encrypted Traffic', description: 'VPN-encapsulated traffic' }],
    interactsWith: ['SEC-03'],
    potentialUseCases: ['PUC4 - Smart Grid'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'SEC-03',
    title: 'WireGuard',
    categorySlug: 'security-tools',
    provider: 'Open Source',
    description: 'Modern VPN protocol',
    type: 'Software',
    trl: { current: 9, expected: 9 },
    license: 'GPL-2.0',
    standards: ['WireGuard'],
    inputs: [{ name: 'Network Traffic', description: 'Traffic to tunnel' }],
    outputs: [{ name: 'Encrypted Traffic', description: 'VPN-encapsulated traffic' }],
    interactsWith: ['SEC-02'],
    potentialUseCases: ['PUC4 - Smart Grid'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'TEST-01',
    title: 'AVL TestGuard',
    categorySlug: 'testing-tools',
    provider: 'AVL',
    description: 'Automotive security testing platform',
    type: 'Software',
    trl: { current: 6, expected: 7 },
    license: 'Proprietary',
    standards: ['ISO 21434', 'SAE J3061'],
    inputs: [{ name: 'Vehicle Data', description: 'Automotive network traffic' }],
    outputs: [{ name: 'Test Results', description: 'Security test findings' }],
    interactsWith: ['TEST-02'],
    potentialUseCases: ['PUC3 - Automotive'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'TEST-02',
    title: 'AVL ThreatGuard',
    categorySlug: 'testing-tools',
    provider: 'AVL',
    description: 'TARA and threat analysis tool',
    type: 'Software',
    trl: { current: 6, expected: 7 },
    license: 'Proprietary',
    standards: ['ISO 21434', 'STRIDE'],
    inputs: [{ name: 'System Model', description: 'Vehicle architecture' }],
    outputs: [{ name: 'Threat Model', description: 'TARA analysis results' }],
    interactsWith: ['TEST-01'],
    potentialUseCases: ['PUC3 - Automotive'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'TEST-03',
    title: 'LearnLib',
    categorySlug: 'testing-tools',
    provider: 'Open Source',
    description: 'Model learning toolkit',
    type: 'Software',
    trl: { current: 7, expected: 8 },
    license: 'Apache-2.0',
    standards: ['Automata Learning'],
    inputs: [{ name: 'System Traces', description: 'Execution traces' }],
    outputs: [{ name: 'Learned Model', description: 'Inferred automaton' }],
    interactsWith: ['TEST-04'],
    potentialUseCases: ['PUC3 - Automotive'],
    repositoryTable: 'OTHER_SERVICES',
  },
  {
    shortName: 'TEST-04',
    title: 'mCRL2',
    categorySlug: 'testing-tools',
    provider: 'Open Source',
    description: 'Formal verification toolkit',
    type: 'Software',
    trl: { current: 7, expected: 8 },
    license: 'Boost',
    standards: ['mCRL2'],
    inputs: [{ name: 'System Spec', description: 'Process algebra specification' }],
    outputs: [{ name: 'Verification Results', description: 'Model checking results' }],
    interactsWith: ['TEST-03'],
    potentialUseCases: ['PUC3 - Automotive'],
    repositoryTable: 'OTHER_SERVICES',
  },
];

const servicesData: ServiceSeed[] = [...intactToolboxServices, ...infrastructureServices];

export const seedServices = async (): Promise<void> => {
  console.log('Seeding services...');

  // Get all categories for lookup
  const categories = await Category.find();
  const categoryMap = new Map(categories.map((c) => [c.slug, c._id]));

  for (const serviceData of servicesData) {
    const existing = await Service.findOne({ shortName: serviceData.shortName });

    if (!existing) {
      const categoryId = categoryMap.get(serviceData.categorySlug);

      if (!categoryId) {
        console.error(`  Category not found for ${serviceData.shortName}: ${serviceData.categorySlug}`);
        continue;
      }

      await Service.create({
        ...serviceData,
        categoryId,
        currentVersion: '1.0.0',
        versions: [
          {
            version: '1.0.0',
            dockerImage: `registry.intact-project.eu/${serviceData.provider.toLowerCase().replace(/\s+/g, '-')}/${serviceData.shortName.toLowerCase()}:v1.0.0`,
            releaseNotes: 'Initial release',
            releasedAt: new Date(),
          },
        ],
      });
      console.log(`  Created service: ${serviceData.shortName}`);
    } else {
      console.log(`  Service exists: ${serviceData.shortName}`);
    }
  }

  console.log('Services seeded successfully');
};
